docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>', views.detail, name="detail"),
    path(r'r/<slug>', views.redir, name="redir"),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>/', views.detail, name="detail"),
    path(r'<slug>/attend', views.attend, name="attend"),
    path(r'<slug>/proxy', views.proxy, name="proxy"),
]

events/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from infos.models import Profile
from datetime import date
import unicodedata
import os

class Place(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=50)

    def __str__(self):
        return "%s (%s)" % (self.name, self.short_name)

class Event(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    desc = models.TextField(default="")
    date = models.DateField()
    place = models.ForeignKey(Place, on_delete=models.PROTECT, null=True, blank=True)
    expected_members = models.ManyToManyField(Profile, blank=True)

    def has_passed(self):
        return self.date < date.today()

    def __str__(self):
        return "[%s] %s" % (self.date, self.name)

class Attendance(models.Model):
    ATTENDANCE_CHOICES = (('Y', 'Présent'),
                          ('N', 'Absent'),
                          ('P', 'Proxy'))
    member = models.ForeignKey(Profile, on_delete=models.CASCADE)
    attendance = models.CharField(max_length = 1, choices=ATTENDANCE_CHOICES, default = 'N')
    proxy_to = models.ForeignKey(Profile, related_name="proxy_for", on_delete=models.CASCADE, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('event', 'member',)

    def __str__(self):
        if self.attendance == 'P':
            return "[%s] %s →  %s" % (self.attendance, self.member.derby_name, self.proxy_to.derby_name)
        else:
            return "[%s] %s" % (self.attendance, self.member.derby_name)

events/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views import generic

from events.models import Event, Attendance
from infos.models import Profile
from datetime import datetime
from pytz import timezone
from django.conf import settings

TZ = timezone(settings.TIME_ZONE)
MAX_PROXY = 3

def get_proxies(event):
    profiles = event.expected_members.filter(has_been_checked = True).order_by('derby_name')
    for profile in profiles:
        profile.possible_proxy = True
        proxy_absent = Attendance.objects.filter(event = event, member = profile, attendance = 'N')
        proxy_from = Attendance.objects.filter(event = event, member = profile, attendance = 'P')
        proxy_to_count = Attendance.objects.filter(event = event, proxy_to = profile, attendance = 'P').count()
        if proxy_absent:
            #Proxy won't be there
            profile.possible_proxy = False
        if proxy_from:
            #Proxy already uses a proxy
            profile.possible_proxy = False
        if proxy_to_count >= MAX_PROXY:
            #Proxy is already used by 3 members
            profile.possible_proxy = False

        yield profile

def has_been_checked(user):
    valid = False
    try:
        valid = user.profile.has_been_checked
    except:
        valid = False
    return valid

@user_passes_test(has_been_checked)
def index(request):
    user = request.user
    now = TZ.localize(datetime.now())
    events = Event.objects.all()
    context = {'events': events}
    return render(request, 'events/index.html', context)

@user_passes_test(has_been_checked)
def detail(request, slug):
    now = TZ.localize(datetime.now())
    user = request.user
    event = get_object_or_404(Event, slug=slug)
    proxies = get_proxies(event)
    member_proxies = Attendance.objects.filter(event=event, proxy_to=user.profile)
    try:
        attendance = Attendance.objects.get(event=event, member=user.profile)
    except Attendance.DoesNotExist:
        attendance = Attendance(event=event, member=user.profile)
    return render(request, 'events/detail.html', {
        'event': event,
        'proxies': proxies,
        'member_proxies': member_proxies,
        'attendance': attendance,
    })

@user_passes_test(has_been_checked)
def attend(request, slug):
    now = TZ.localize(datetime.now())
    event = get_object_or_404(Event, slug=slug)
    user = request.user
    proxy_to = request.POST.get('proxy', None)
    present = request.POST.get('Y', False)
    proxy = request.POST.get('P', False)
    absent = request.POST.get('N', False)
    try:
        attendance = Attendance.objects.get(event=event, member=user.profile)
    except Attendance.DoesNotExist:
        attendance = Attendance(event=event, member=user.profile)
    if present:
        attendance.attendance = 'Y'
        attendance.proxy_to = None
        attendance.accepted = True
    elif proxy:
        attendance.attendance = 'P'
        try:
            proxy_profile = Profile.objects.get(pk = proxy_to)
        except Profile.DoesNotExist:
            attendance.attendance = 'N'
            proxy_profile = None
        attendance.proxy_to = proxy_profile
        attendance.accepted = False
        # Remove all proxy requests
        Attendance.objects.filter(event=event, proxy_to=user.profile).delete()
    else:
        attendance.attendance = 'N'
        attendance.proxy_to = None
        attendance.accepted = True
        # Remove all proxy requests
        Attendance.objects.filter(event=event, proxy_to=user.profile).delete()
        Attendance.objects.filter(event=event, member=user.profile).delete()

    attendance.save()
    return HttpResponseRedirect(reverse('events:detail', args=(slug,)))

@user_passes_test(has_been_checked)
def proxy(request, slug):
    now = TZ.localize(datetime.now())
    event = get_object_or_404(Event, slug=slug)
    member_id = request.POST.get('member_id', None)
    proxy_member = get_object_or_404(Profile, id=member_id)
    user = request.user
    try:
        attendance = Attendance.objects.get(event=event, member=proxy_member, proxy_to=user.profile)
    except Attendance.DoesNotExist:
        return HttpResponseRedirect(reverse('events:detail', args=(slug,)))

    accept = request.POST.get('proxy_accept', False)
    deny = request.POST.get('proxy_deny', False)
    if accept:
        attendance.accepted = True
        attendance.save()
        try:
            self_att = Attendance.objects.get(event=event, member=user.profile)
        except Attendance.DoesNotExist:
            self_att = Attendance(event=event, member=user.profile)
        self_att.attendance = 'Y'
        self_att.proxy_to = None
        self_att.accepted = True
        self_att.save()
    elif deny:
        attendance.delete()

    return HttpResponseRedirect(reverse('events:detail', args=(slug,)))

events/templates/events/detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="cover">
  <h1 class="cover-heading">[{{ event.date }}] {{ event.name }}</h1>
  {% if event.place %}
  <h3 class="cover-heading"><span class="glyphicon glyphicon-map-marker"></span>{{ event.place.name }}</h3>
  {% endif %}
  <div class="lead">
{% if error_message %}
<div class="alert alert-info" role="alert">
  {{ error_message }}
</div>
{% endif %}

<div class="alert lead">
{{ event.desc|linebreaks }}
</div>
{% if event.has_passed %}
<div class="alert lead">
Cet événement est passé.
</div>
{% else %}
<!-- Is this member proxy ? -->
<div>
{% for member_proxy in member_proxies %}
{% if member_proxy.accepted %}
<p class="alert alert-success">
Tu as accepté la demande de procuration de <b>{{ member_proxy.member.derby_name }}</b>.<br />
En cas d'absence de sa part, tu représenteras <b>{{ member_proxy.member.derby_name }}</b> le {{ event.date }}.
Nous comptons donc sur ta présence :).
</p>
{% else %}
<form class="alert alert-warning" action="{% url 'events:proxy' event.slug %}" method="post">
{% csrf_token %}
<b>{{ member_proxy.member.derby_name }}</b> te propose son pouvoir de vote pour le {{ event.date }}.<br />
Acceptes-tu cette procuration ?
<input type="hidden" name="member_id" value="{{ member_proxy.member.id }}" />
<input class="btn btn-lg btn-success" type="submit" name="proxy_accept" value="oui" />
<input class="btn btn-lg btn-danger" type="submit" name="proxy_deny" value="non" />
</form>
</p>
{% endif %}
{% endfor %}
</div>
<!-- Will this member come ? -->
<div>
{% if attendance.attendance == 'Y' %}
<p class="alert alert-success">
Tu as confirmé ta participation à cet événement. 
</p>
{% elif attendance.attendance == 'N' %}
<p class="alert alert-danger">
Tu n'as pas confirmé ta participation à cet événement. 
<span class="glyphicon glyphicon-info-sign"
      title="Si tu avais fait une demande de procuration et qu'elle n'apparaît pas ici, c'est que cette procuration n'est plus possible ou a été refusée">&nbsp;
</span>
</p>
{% elif attendance.attendance == 'P' %}
<p class="alert alert-info">
Tu as demandé une procuration à <b>{{ attendance.proxy_to.derby_name }}</b>. <br />
</p>
{% if attendance.accepted %}
<p class="alert alert-success">
<b>{{ attendance.proxy_to.derby_name }}</b> a accepté ton pouvoir pour cet événement. A défaut de ta présence, 
<b>{{ attendance.proxy_to.derby_name }}</b> votera pour toi le {{ event.date }}.
</p>
{% else %}
<p class="alert alert-warning">
<b>{{ attendance.proxy_to.derby_name }}</b> n'a pas encore accepté ton pouvoir pour cet événement. <br/>
Si tu refais une demande de procuration ci-dessous, ta première demande sera annulée et
remplacée. 
</p>
{% endif %}
{% endif %}
<form class="lead" action="{% url 'events:attend' event.slug %}" method="post">
{% csrf_token %}
  <div class="form-group">
  <hr />
  Je compte assister en personne à cet événement.
  <input class="btn-block btn btn-lg btn-success" style="white-space: normal;" type="submit" name="Y" 
         value="Je viens." /><br />
  <hr />
  Pour cet événement, je souhaite donner pouvoir de vote à 
  <select name="proxy" class="custom-select custom-select-lg mb-3">
    <option disabled selected value></option>
    {% for proxy in proxies %}
      {% if proxy.possible_proxy and not proxy == user.profile and not proxy == attendance.proxy_to %}
        <option value="{{ proxy.id }}">{{ proxy.derby_name }} (#{{ proxy.derby_number }})</option>
      {% else %}
        <option value="{{ proxy.id }}" disabled>{{ proxy.derby_name }} (#{{ proxy.derby_number }})</option>
      {% endif %}
    {% endfor %}
  </select>.
  <span class="glyphicon glyphicon-info-sign"
        title="Un membre apparaît grisé s'il a lui-même demandé une procuration, s'il ne vient pas ou s'il a déjà 3 demandes de procuration en cours.">&nbsp;
  </span>
  <input class="btn btn-block  btn-lg btn-info" style="white-space: normal;" type="submit" name="P"
         value="Je valide ma demande de procuration et je refuse donc les demandes de procuration qui m'ont été adressées." /><br />
  <hr />
  Je ne compte pas participer à cet événement et ne souhaite pas y être représenté.
  <input class="btn btn-block btn-lg btn-danger" style="white-space: normal;" type="submit" name="N" 
         value="Je ne viens pas et je refuse donc toutes les demandes de procuration qui m'ont été adressées." /><br />
  <hr />
  </div>
</form>
</div>
{% endif %}
{% endblock %}

events/templates/events/index.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <h1 class="cover-heading">
    <span class="glyphicon glyphicon-calendar">&nbsp;</span>
    Événements
  </h1>
  <div class="lead">
    <ul>
    {% for event in events %}
      <li>
        <a href="{% url 'events:detail' event.slug %}" title="{{ event.name }}">[{{ event.date }}] {{ event.name }}</a>
      </li>
    {% endfor %}
  </div>
</div>
{% endblock %}