docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>', views.detail, name="detail"),
    path(r'r/<slug>', views.redir, name="redir"),
]

infos/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path(r'', views.profile, name="profile"),
    path(r'list', views.index, name="index"),
    path(r'memberlist', views.memberlist, name="memberlist"),
    path(r'success', views.success, name="success"),
    path(r'edit', views.edit, name="edit"),
    path(r'membership', views.membership, name="membership"),
    path(r'create', views.create, name="create"),
    path(r'subscribe', views.subscribe, name="subscribe"),
    path(r'health_cert', views.health_cert_redir, name="health_cert_redir"),
    path(r'health_cert/<filename>', views.health_cert, name="health_cert"),
    path(r'payments', views.payments, name="payments"),
    path(r'validate', views.validate_payments, name="validate_payments"),
    path(r'<derby_number>', views.teammate, name="teammate"),
]

infos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import unicodedata
import os
import string


# Create your models here.
class Profile(models.Model):

    # bypass for votes
    has_been_checked = models.BooleanField(default = False)

    # actual profile
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    derby_name = models.CharField(max_length=200)
    derby_number = models.CharField(max_length=5, blank=True)
    fb_id = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return "%s (#%s)" % (self.derby_name, self.derby_number)

    def slug(self):
        return ''.join(e for e in str(self) if e.isalnum())

class Member(models.Model):
    FFRS_CHOICES = (('PComp', 'Licence "en patins" par la Panam Squad'),
                    ('PFoot', 'Licence "non-pratiquant" par la Panam Squad'),
                    ('NoLic', "Licence par un autre club ou pas besoin de licence FFRS"))

    ROLE_CHOICES = (('P', 'Jouer'),
                    ('O', 'Officier/Arbitrer'),
                    ('C', 'Coacher'),
                    ('A', 'Autre'),)

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    real_name = models.CharField(max_length=200)
    has_been_processed = models.BooleanField(default = False)
    birth_date = models.DateField(blank=True, null=True)
    post_address = models.CharField(max_length=200, blank=True)
    postal_code = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=50, blank=True)
    contact_phone = models.CharField(max_length=15, blank=True)
    contact_email = models.CharField(max_length=50, blank=True)

    ffrs_status = models.CharField(max_length=8, choices=FFRS_CHOICES, default='PComp')
    role = models.CharField(max_length=2, choices=ROLE_CHOICES, default='P')

    submitted = models.BooleanField(default=False)
    validated = models.BooleanField(default=False)
    has_paid = models.BooleanField(default=False)

    health_cert = models.FileField(upload_to='health_certs', blank=True)
    keep_health_cert = models.BooleanField(default=False)

    def birth_date_short(self):
        try:
            value = self.birth_date.strftime('%Y-%m-%d')
        except:
            value = ""
        return value

    def subscription_dues(self):
        dues = 0
        if self.role in ('P',):
            dues += 75
        elif self.role in ('A', 'O', 'C',):
            dues += 10
        if self.ffrs_status in ('PComp', 'PFoot'):
            dues += 40
        return dues

    def health_cert_url(self):
        name = "%s%s" % (self.profile.derby_number, self.profile.derby_name)
        cert_name = unicodedata.normalize('NFKD', name).replace(' ', '')
        _, extension = os.path.splitext(self.health_cert.name)
        return cert_name+extension

    def display_name(self):
        return "%s (#%s)" % (self.profile.derby_name, self.profile.derby_number)

    display_name.short_description = 'Profile'

    def __str__(self):
        return self.display_name()


class ProfileGroup(models.Model):
    name = models.CharField(max_length=200)
    profiles = models.ManyToManyField(Profile)

    def user_count(self):
        return self.profiles.count()

    def __str__(self):
        return "%s (%s)" % (self.name, self.profiles.count())

infos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test

from infos.models import Profile, ProfileGroup, Member
from datetime import datetime
from django.conf import settings

def has_been_checked(user):
    valid = False
    try:
        valid = user.profile.has_been_checked
    except:
        valid = False
    return valid

def has_membership(user):
    valid = False
    try:
        valid = bool(user.profile.member)
    except:
        valid = False
    return valid

def _can_validate_paid(user):
    valid = False
    group = ProfileGroup.objects.get(name='_can_validate_paid')
    usergroups = []
    try:
        usergroups = user.profile.profilegroup_set.all()
        valid = group in usergroups
    except:
        valid = False
    return valid
    

@login_required
def profile(request):
    """Edit my profile"""
    user = request.user
    context = {'user': user, 'edit_mode': True}
    return render(request, 'infos/profile.html', context)

@login_required
def membership(request, err=None, succ=None, info=None):
    """Edit my panamsquad membership"""
    user = request.user
    roles = Member.ROLE_CHOICES
    ffrs = Member.FFRS_CHOICES
    context = {'user': user, 'edit_mode': True, 'roles': roles, 'ffrs': ffrs}
    context.update({'error_message': err, 'success_message': succ, 'info_message': info})
    return render(request, 'infos/membership.html', context)

@login_required
def success(request):
    user = request.user
    success_msg = "Merci d'avoir créé ton profil !"
    context = {'success_message': success_msg}
    return render(request, 'infos/profile.html', context)

@user_passes_test(has_been_checked)
def index(request):
    members = Member.objects.filter().order_by('role')
    return render(request, 'infos/index.html', {'members': members, 'filter_name': "adhérents"})

@user_passes_test(has_been_checked)
def memberlist(request):
    members = Member.objects.filter(submitted=True, has_paid=True).order_by('role')
    return render(request, 'infos/index.html', {'members': members, 'filter_name': "adhérents"})

@user_passes_test(has_been_checked)
def teammate(request, derby_number):
    """Check my teammate's profile"""
    user = request.user
    return render(request, 'infos/teammate.html', {'user': user, 'edit_mode': False})

@login_required
def create(request):
    derby_name = pk=request.POST['derby_name']
    derby_number = pk=request.POST['derby_number']
    if not derby_number:
        derby_number = '____'

    if not all((derby_name, derby_number,)):
        error_msg = "Il est nécessaire de renseigner un derby name."
        return render(request, 'infos/profile.html', {'error_message': error_msg})

    profile = Profile()
    profile.user = request.user
    profile.derby_name = derby_name
    profile.derby_number = derby_number
    profile.save()
    return HttpResponseRedirect(reverse('profile:success'))

@login_required
def subscribe(request):
    real_name = request.POST['real_name']
    birth_date = request.POST['birth_date']
    post_address = request.POST['post_address']
    postal_code = request.POST['postal_code']
    city = request.POST['city']
    contact_phone = request.POST['contact_phone']
    contact_email = request.POST['contact_email']
    role = request.POST['role']
    ffrs_status = request.POST['ffrs_status']
    save = bool(request.POST.get('save', False))
    submit = bool(request.POST.get('submit', False))
    data_ok = bool(request.POST.get('data_ok', False))
    ri_ok = bool(request.POST.get('ri_ok', False))
    health_cert = request.FILES.get('health_cert', None)
    keep_health_cert = bool(request.POST.get('keep_health_cert', False))
    try:
        member = Member.objects.get(profile=request.user.profile)
    except:
        member = Member()
        member.profile = request.user.profile

    member.real_name = real_name
    member.birth_date = birth_date
    member.post_address = post_address
    member.postal_code = postal_code
    member.city = city
    member.contact_phone = contact_phone
    member.contact_email = contact_email
    member.role = role
    member.ffrs_status = ffrs_status
    if health_cert:
        member.health_cert = health_cert
    member.keep_health_cert = keep_health_cert
    member.save()

    if submit:
    # Check that the mandatory box
        if not data_ok:
            error_msg = "Il faut accepter que la Panam Squad utilise les informations fournies pour adhérer."
            return membership(request, err=error_msg)
        if not ri_ok:
            error_msg = "Il faut accepter le Règlement Intérieur pour adhérer."
            return membership(request, err=error_msg)
        if member.ffrs_status in ('PComp',) and not member.health_cert:
            error_msg = "Il te faut avoir un certificat médical dans ton dossier pour acquérir ce type de license FFRS."
            return membership(request, err=error_msg)
        member.submitted = True
        member.save()
        msg = "Merci d'avoir transmis ton dossier."
        return membership(request, succ=msg)

    
    msg = "Ton dossier a bien été sauvegardé."
    return membership(request, succ=msg)

@login_required
def edit(request):
    return HttpResponseRedirect(reverse('profile:success'))

@user_passes_test(has_membership)
def health_cert_redir(request):
    member = request.user.profile.member
    if member.health_cert:
        cert_url = member.health_cert_url()
        return HttpResponseRedirect(reverse('profile:health_cert', args=(cert_url,)))
    return HttpResponseRedirect(reverse('profile:profile'))

@user_passes_test(has_been_checked)
def health_cert(request, filename):
    user = request.user
    cert_file = user.profile.member.health_cert
    return HttpResponse(cert_file.read(), content_type='application/octet-stream')

@user_passes_test(_can_validate_paid)
def validate_payments(request):
    for post_var in request.POST.keys():
        if post_var.startswith('paid_'):
            member_id = post_var[5:]
            member = Member.objects.get(id=member_id)
            print (member, repr(request.POST[post_var]))
            if request.POST[post_var] == 'Y':
                member.has_paid = True
            elif request.POST[post_var] == 'N':
                member.has_paid = False
            member.save()
    submitted_members = Member.objects.filter(submitted=True).order_by('profile__derby_name')
    msg = "Les paiements ont été enregistrés."
    context = {'submitted_members': submitted_members, 'success_message': msg}
    return render(request, 'infos/payments.html', context)

@user_passes_test(_can_validate_paid)
def payments(request):
    submitted_members = Member.objects.filter(submitted=True).order_by('has_paid', 'profile__derby_name')
    return render(request, 'infos/payments.html', {'submitted_members': submitted_members})

infos/templates/infos/index.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <div class="lead">
  <h1 class="cover-heading">
    Liste des {{filter_name}}
  </h1>
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}
{% if success_message %}
<div class="alert alert-success" role="alert">
  {{ success_message }}
</div>
{% endif %}
<div>
  <table class="table">
  <thead>
    <th scope="col">#</th>
    <th scope="col">Derby name</th>
    <th scope="col">Role principal</th>
    <th scope="col">Dossier soumis</th>
    <th scope="col">Payé</th>
    <th scope="col">Lien Facebook</th>
  </thead>
  <tbody>
{% for member in members %}
  {% if member.submitted %}
    {% if member.has_paid %}
      <tr>
    {%else%}
      <tr class="bg-warning">
    {%endif%}
  {% else %}
    <tr class="bg-danger">
  {% endif %}
    <td>{{ member.profile.derby_number }}</td>
    <td>{{ member.profile.derby_name }}</td> 
    <td>{{ member.role }}</td> 
    <td>{{ member.submitted }}</td> 
    <td>{{ member.has_paid }}</td> 
    <td>
{% if member.profile.fb_id %}
    <a href="https://www.facebook.com/{{ member.profile.fb_id }}" target="_blank">
      <span class="glyphicon glyphicon-pushpin"></span>
    </a>
{% endif %}
    </td> 
  </tr>
{% endfor %}
  </tbody>
  </table>
</div>
{% endblock %}

infos/templates/infos/membership.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <div class="lead">
  <h1 class="cover-heading">
    <!--<span class="glyphicon glyphicon-user">&nbsp;</span>-->
    Mon bulletin d'adhésion
  </h1>
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}
{% if success_message %}
<div class="alert alert-success" role="alert">
  {{ success_message }}
</div>
{% endif %}

<div>
{% if not user.profile.member or not user.profile.member.submitted %}
  <form class="form-horizontal" action="{% url 'profile:subscribe' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="derby_name" class="control-label">
      Derby name :
    </label>
    <input type="text" class="form-control"
      value="{{ user.profile.derby_name }}"
      id="derby_name" name="derby_name" disabled />
    <label for="derby_number" class="control-label">
      Derby number :
    </label>
    <input type="text" class="form-control"
      value="{{ user.profile.derby_number }}"
      id="derby_number" name="derby_number" disabled />
  </div>
  <div class="form-group">
    <label for="real_name" class="control-label">
      Nom d'usage :
    </label>
    <input type="text" class="form-control"
      id="real_name" name="real_name"
      value="{{ user.profile.member.real_name }}"
      placeholder="Prénom Nom" />
    <label for="birth_date" class="control-label">
      Date de naissance :
    </label>
    <input type="date" class="form-control"
      id="birth_date" name="birth_date"
      value="{{ user.profile.member.birth_date_short }}" />
  </div>

  <hr />
  <div class="form-group">
    <label for="post_address" class="control-label">
      Adresse :
    </label>
    <input type="text" class="form-control"
      id="post_address" name="post_address"
      value="{{ user.profile.member.post_address }}" />
    <label for="postal_code" class="control-label">
      Code postal :
    </label>
    <input type="text" class="form-control"
      id="postal_code" name="postal_code"
      value="{{ user.profile.member.postal_code }}" />
    <label for="city" class="control-label">
      Ville :
    </label>
    <input type="text" class="form-control"
      id="city" name="city"
      value="{{ user.profile.member.city }}" />
  </div>

  <hr />
  <div class="form-group">
    <label for="contact_phone" class="control-label">
      Numéro de téléphone :
    </label>
    <input type="tel" class="form-control"
      id="contact_phone" name="contact_phone"
      value="{{ user.profile.member.contact_phone }}" />
    <label for="contact_email" class="control-label">
      Email :
    </label>
    <input type="email" class="form-control"
      id="contact_email" name="contact_email"
      value="{{ user.profile.member.contact_email }}" />
  </div>

  <hr />
  <div class="form-group">
    <label class="control-label">Rôle principal au sein de la Panam Squad : </label>
    <p><small>
    Ton rôle au sein de la Panam Squad détermine le montant de ton adhésion
    et tes accès à certaines ressources. <br />
    </small></p>
    <p class="alert alert-info"><small>
    Pour la saison 2020/2021, le montant de l'adhésion en tant que joueur·euse
    s'élève à <b>75€</b> pour l'année. <br />
    Pour la saison 2020/2021, le montant de l'adhésion en tant qu'officiel·le
    s'élève à <b>10€</b> pour l'année. <br />
    Pour la saison 2020/2021, le montant de l'adhésion en tant que coach·e
    s'élève à <b>10€</b> pour l'année. <br />
    </small></p>
    {% for role_slug,role_desc in roles %}
    <div class="radio">
      <label><input type="radio" name="role"
      {% if user.profile.member.role == role_slug %}
      value="{{ role_slug }}" checked />{{ role_desc }}</label>
      {% else %}
      value="{{ role_slug }}" />{{ role_desc }}</label>
      {% endif %}
    </div>
    {% endfor %}
  </div>

  <hr />
  <div class="form-group">
    <label class="control-label">Licence FFRS :</label>
    <p><small>
      Si tu es absolument certain·e de ne pas patiner/rouler cette année,
      même en randonnée, mais que tu souhaites pouvoir officier sur des 
      matchs officiels, une licence "non-pratiquant" t'est nécessaire.<br />
    </small></p>
    <p class="alert alert-info"><small>
      La prise de licence FFRS, qu'elle soit avec ou sans patins, s'élève
      à <b>40€</b>.
    </small></p>

    {% for ffrs_slug,ffrs_desc in ffrs %}
    <div class="radio">
      <label><input type="radio" name="ffrs_status"
      {% if user.profile.member.ffrs_status == ffrs_slug %}
      value="{{ ffrs_slug }}" checked />{{ ffrs_desc }}</label>
      {% else %}
      value="{{ ffrs_slug }}" />{{ ffrs_desc }}</label>
      {% endif %}
    </div>
    {% endfor %}
  </div>

  <div class="form-group">
    <label class="control-label">Certficat médical :</label>
    <p><small>
       Si tu souhaites que la Panam Squad gère pour toi une licence "avec
       patins", merci de transmettre un certificat médical en cours de
       validité permettant "la pratique du Roller Derby
       <b>en compétition</b>".<br />
    </small></p>
    <p class="alert alert-warning"><small>
      Le cas échéant, ne soumet pas ton adhésion avant d'avoir vérifié
      que ton certificat est bien valide (qu'il n'a pas plus de 3 ans).
    </small></p>
    <center>
    <label>
      <input type=file name="health_cert" class="form-control-file" />
    </label>
    {% if user.profile.member.health_cert %}
    <p>
      <a href="{% url "profile:health_cert_redir" %}">
        certificat actuel</a>
    </p>
    {% endif %}
    </center>
    <label class="form-check-label">
      <input class="form-check-input" type="checkbox"
      {% if user.profile.member.keep_health_cert %}
        name="keep_health_cert" value="yes" checked />
      {% else %}
        name="keep_health_cert" value="yes" />
      {% endif %}
      <small>
        En cochant cette case, j'autorise la Panam Squad à conserver et
        archiver mon certificat médical pour préparer mon éventuel
        bulletin d'adhésion de la saison prochaine.
      </small>
    </label>
  </div>
  <hr />
  <div class="form-group row">
  <div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox"
    name="ri_ok" value="yes" />
    <small>
    J'ai lu et j'accepte le <a href="https://my.panamsquad.com/docs/r/RI">
    Règlement Intérieur de la Panam Squad</a> et je m'engage à respecter le 
    <a href="https://mrda.org/resources/code-of-conduct/">Code de Conduite de la MRDA</a>, 
    fédération dont la Panam Squad fait partie et son 
    <a href="https://my.panamsquad.com/docs/r/mrda-sexual-harassment-policy">Annexe
    sur le harcèlement sexuel</a>.
    </small>
  </label>
  </div>
  <div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox"
    name="data_ok" value="yes" />
    <small>
    Je certifie que ces informations sont exactes et je consens à ce qu'elles
    soient utilisées afin de gérer mon adhésion à la Panam Squad. Elles 
    pourront être transmises à la FFRS dans le cas de l'acquisition d'une 
    licence en mon nom. 
    </small>
  </label>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
      <input type="submit" name="save" class="btn btn-lg btn-default"
       value="Sauvegarder" />
      <input type="submit" name="submit" class="btn btn-lg btn-success"
       value="Envoyer mon dossier" />
    </div>
  </div>
  </form>
</div>
{% else %}
<div class="alert alert-info" role="alert">
Ton bulletin d'adhésion est en cours de traitement. <br />
Contacte un·e administrateur·rice si tu souhaites pouvoir le modifier.
</div>
{% if not user.profile.member.has_paid %}
<div class="alert alert-warning" role="alert">
Il te reste {{ user.profile.member.subscription_dues }}€ à verser à la
Panam Squad. <br />
Il est possible que ce traitement soit en cours de notre côté.<br />
N'hésite pas à contacter la trésorerie
(<a href="https://www.facebook.com/Kiki.kilian.garnier"><b>Kiki</b></a> ou
<a href="https://www.facebook.com/npiffeteau"><b>La Piffe</b></a>) si tu as une question.<br />
<center>
<a class="btn btn-default" href="{% url 'docs:redir' 'iban' %}">Payer par virement</a>
<br />ou<br />
<a class="btn btn-default" href="https://paypal.me/PanamSquad/{{ user.profile.member.subscription_dues }}">par Paypal</a>
<br />ou<br />
par chèque à l'ordre de la Panam Squad.
<br />ou<br />
en liquide ou par carte auprès de la trésorerie.
</center>
</div>
{% endif %}
{% endif %}
  </div>
</div>
{% if success_message %}
<script>
  function redirect(){
     window.location.href = "{% url 'profile:membership' %}";
  }
  setTimeout(redirect, 1000);
</script>
{% endif %}
{% endblock %}

infos/templates/infos/payments.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <div class="lead">
  <h1 class="cover-heading">
    Valider les paiements
  </h1>
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}
{% if success_message %}
<div class="alert alert-success" role="alert">
  {{ success_message }}
</div>
{% endif %}
<div>
  <form class="form-horizontal" action="{% url 'profile:validate_payments' %}" method="post">
  {% csrf_token %}
  <table class="table">
  <thead>
    <th scope="col">#</th>
    <th scope="col">Derby name</th>
    <th scope="col">Nom d'usage</th>
    <th scope="col">Doit verser</th>
    <th scope="col">A payé</th>
  </thead>
  <tbody>
{% for member in submitted_members %}
{% if member.subscription_dues >= 0 %}
  <tr class="">
    <td>{{ member.profile.derby_number }}</td>
    <td>{{ member.profile.derby_name }}</td> 
    <td>{{ member.real_name }}</td> 
    <td>{{ member.subscription_dues }}€</td> 
    <td class="" data-toggle="">
    {% if not member.has_paid %}
      <label class="active">
      <input type="radio" name="paid_{{member.id}}" value="N" autocomplete="off" checked />non
      </label>
      <label class="">
      <input type="radio" name="paid_{{member.id}}" value="Y" autocomplete="off">oui
      </label>
    {% else %}
      <label class="">
      <input type="radio" name="paid_{{member.id}}" value="N" autocomplete="off">non
      </label>
      <label class="active">
      <input type="radio" name="paid_{{member.id}}" value="Y" autocomplete="off" checked />oui
      </label>
    {% endif %}
    </td> 
  </tr>
{% endif %}
{% endfor %}
  </tbody>
  </table>
  <input type="submit" class="btn btn-lg btn-info" value="Valider les paiements" />
  </form>
</div>
{% if success_message %}
<script>
  function redirect(){
     window.location.href = "{% url 'profile:payments' %}";
  }
  setTimeout(redirect, 1000);
</script>
{% endif %}
{% endblock %}

infos/templates/infos/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  {% if not user.profile.derby_name or not user.profile.derby_number %}
<h2>Cr&eacute;er un profil</h2>
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}
{% if success_message %}
<div class="alert alert-success" role="alert">
  {{ success_message }}
</div>
{% endif %}
<p>
Afin d'acc&eacute;der aux diff&eacute;rentes fonctionalit&eacute;s de cet extranet, 
et de pouvoir t'itendifier plus facilement par la suite merci de cr&eacute;er un profil.<br/>
In order to access the functionalities of this site, and to identify yourself more easily
later, please, create a profile.
</p>
<div class="alert alert-info" role="alert">
  La cr&eacute;ation d'un profil sur l'extranet Panam Squad <b>ne</b> constitue <b>pas</b> une
  adh&eacute;sion. <br/>
  Creating a profile on this site is <b>not</b> a subscription for any Panam Squad membership.
</div>
  <form class="" action="{% url 'profile:create' %}" method="post">
  {% csrf_token %}
  <div class="form-group row">
    <label for="derby_name" class="col-sm-2 col-form-label">
      Derby name :
    </label>
    <input type="text" class="form-control col-sm-4"
      value="{{ user.profile.derby_name }}"
      placeholder="Derby Name"
      id="derby_name" name="derby_name"/>
  </div>
  <div class="form-group row">
    <label for="derby_number" class="col-sm-2 col-form-label">
      Derby number :
    </label>
    <input type="text" class="form-control col-sm-4"
      value="{{ user.profile.derby_number }}"
      placeholder="XXXX"
      id="derby_number" name="derby_number"/>
  </div>
  <div class="form-group">
    <div class="">
      <input type="submit" value="Ok" class="btn btn-lg btn-outline-primary" />
    </div>
  </div>
  </form>
  {% else %}
  <h1 class="cover-heading">
    <!--<span class="glyphicon glyphicon-user">&nbsp;</span>-->
    Mon profil
  </h1>
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}
{% if success_message %}
<div class="alert alert-success" role="alert">
  {{ success_message }}
</div>
{% endif %}
<div class="alert alert-info" role="alert">
  Si tu souhaites modifier ton derby name ou ton numéro, contacte un·e administrateur·rice.
</div>

  <form class="form-horizontal" action="{% url 'profile:edit' %}" method="post">
  <div class="form-group">
    <label class="control-label col-sm-4">Derby name:</label>
    <div class="col-sm-8">
      <p class="form-control-static">
        {{ user.profile.derby_name }}
      </p>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-4">Derby number:</label>
    <div class="col-sm-8">
      <p class="form-control-static">
        {{ user.profile.derby_number }}
      </p>
    </div>
  </div>
<!--
  {% csrf_token %}
  <div class="form-group">
    <div class="col-sm-offset-10 col-sm-10">
      <input type="submit" class="btn btn-info" value="Mettre à jour" />
    </div>
  </div>
-->
  </form>
  {% endif %}
  </div>
</div>
{% if success_message %}
<script>
  function redirect(){
     window.location.href = "/";
  }
  setTimeout(redirect, 3000);
</script>
{% endif %}
{% endblock %}