derby/urls.py
from django.urls import path
from . import views

app_name = 'derby'
urlpatterns = [
    path(r'profile', views.profile, name="profile"),
    path(r'update_profile', views.profile_update, name="profile_update"),
    path(r'trainings', views.trainings, name="trainings"),
    path(r'training/<date>', views.training, name="training"),
    path(r'presences', views.presences, name="presences"),
    path(r'exports', views.export_form, name="export_form"),
    path(r'export', views.profile_export, name="profile_export"),
    path(r'sponsor_emails.txt', views.mail_export, name="mail_export"),
]

docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>', views.detail, name="detail"),
    path(r'r/<slug>', views.redir, name="redir"),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>/', views.detail, name="detail"),
    path(r'<slug>/attend', views.attend, name="attend"),
    path(r'<slug>/proxy', views.proxy, name="proxy"),
]

infos/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path(r'', views.profile, name="profile"),
    path(r'list', views.index, name="index"),
    path(r'memberlist', views.memberlist, name="memberlist"),
    path(r'success', views.success, name="success"),
    path(r'edit', views.edit, name="edit"),
    path(r'membership', views.membership, name="membership"),
    path(r'create', views.create, name="create"),
    path(r'subscribe', views.subscribe, name="subscribe"),
    path(r'health_cert', views.health_cert_redir, name="health_cert_redir"),
    path(r'health_cert/<filename>', views.health_cert, name="health_cert"),
    path(r'payments', views.payments, name="payments"),
    path(r'validate', views.validate_payments, name="validate_payments"),
    path(r'<derby_number>', views.teammate, name="teammate"),
]

votes/urls.py
from django.urls import path
from . import views

app_name = 'votes'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>/', views.detail, name="detail"),
    path(r'<slug>/results', views.results, name="results"),
    path(r'<slug>/vote', views.vote, name="vote"),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Password(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    login = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return "%s (%s)" % (self.name, self.url)

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse


@login_required
def home(request):
    try:
        profile = request.user.profile
    except:
        return HttpResponseRedirect(reverse('profile:profile'))
    can_validate_paid = profile.profilegroup_set.filter(name='_can_validate_paid').exists()
    can_see_variousinfos = profile.profilegroup_set.filter(name='_can_see_variousinfos').exists()
    can_see_sponsoremails = profile.profilegroup_set.filter(name='_can_see_sponsoremails').exists()
    disabled_class = ""
    if not profile.has_been_checked:
        disabled_class = "disabled"
    context = {
               'can_validate_paid': can_validate_paid,
               'can_see_variousinfos': can_see_variousinfos,
               'can_see_sponsoremails': can_see_sponsoremails,
               'maybe_disabled': disabled_class}
    return render(request, 'core/home.html', context)

def privacy(request):
    return render(request, 'core/privacy.html')

core/templates/core/home.html
{% extends 'base.html' %}
{% block content %}
  <div class="cover">
  <p class="lead">
  Bienvenue dans l'extranet de la Panam Squad.<br />
  Ce portail contient de nombreuses fonctionnalit&eacute;s et nous avons essay&eacute;
  de le rendre le plus intuitif possible.
  </p>
{% if not user.profile.has_been_checked %}
<div class="alert alert-warning" role="alert">
  Certaines fonctionalités de ce site te sont encore inaccessibles car ton compte 
  est en cours de validation par un·e administrateur·rice (sans doute 
  <a class="" target="blank" href="https://www.facebook.com/la.mandale"><b>La Mandale</b></a>).<br />
  N'hésite pas à le contacter si tu es bien membre de la Panam Squad.
</div>
{% endif %}
  <div class="list-group lead">
    {% if not user.profile.member or not user.profile.member.has_been_processed %}
      {% if not user.profile.member.has_paid %}
        {% if not user.profile.member.submitted %}
          <a class="list-group-item list-group-item-action list-group-item-info"
             href="{% url 'profile:membership' %}">
        {% else %}
          <a class="list-group-item list-group-item-action list-group-item-warning"
             href="{% url 'profile:membership' %}">
        {% endif %}
      {% else %}
      <a class="list-group-item list-group-item-action list-group-item-success"
         href="{% url 'profile:membership' %}">
      {% endif %}
        <span class="glyphicon glyphicon-leaf">&nbsp;</span>
        Adhésion
        {% if user.profile.member and user.profile.member.submitted and not user.profile.member.has_paid %}
          ({{ user.profile.member.subscription_dues }}€)
        {% endif %}
      </a>
    {% endif %}
      <a class="list-group-item list-group-item-action {{ maybe_disabled }}"
        href="{% url 'events:index' %}">
        <span class="glyphicon glyphicon-calendar">&nbsp;</span>
        Evénements à venir
      </a>
      <a class="list-group-item list-group-item-action {{ maybe_disabled }}"
         href="{% url 'opinions:index' %}">
        <span class="glyphicon glyphicon-comment">&nbsp;</span>
        Donne ton opinion
      </a>
      <a class="list-group-item list-group-item-action {{ maybe_disabled }}"
         href="{% url 'votes:index' %}">
        <span class="glyphicon glyphicon-bullhorn">&nbsp;</span>
        Votes
      </a>
      <a class="list-group-item list-group-item-action {{ maybe_disabled }}"
        href="{% url 'docs:index' %}">
        <span class="glyphicon glyphicon-file">&nbsp;</span>
        Documents et fichiers
      </a>
    {% if can_see_variousinfos or user.is_staff %}
      <a class="list-group-item list-group-item-action"
         href="{% url 'derby:export_form' %}">
        <span class="glyphicon glyphicon-list-alt">&nbsp;</span>
        Fiches membres
      </a>
    {% endif %}
    {% if can_validate_paid %}
      <a class="list-group-item list-group-item-action"
         href="{% url 'profile:payments' %}">
        <span class="glyphicon glyphicon-eur">&nbsp;</span>
        Valider les paiements
      </a>
    {% endif %}
    {% if can_see_sponsoremails %}
      <a class="list-group-item list-group-item-action"
         href="{% url 'derby:mail_export' %}">
        <span class="glyphicon glyphicon-th-list">&nbsp;</span>
        Emails des membres pour sponsoring
      </a>
    {% endif %}
  </div>
  </p>
  </div>
{% endblock %}

core/templates/core/privacy.html
{% extends 'base.html' %}
{% block content %}
  <div class="inner cover">
    <h1 class="cover-heading">Mentions légales</h1>
    <h3>Intranet de la Panam Squad</h3>
    <p>
    Sur son intranet, la Panam Squad propose des liens vers d'autres sites. La Panam Squad
    n'exerce aucun contrôle sur les sites web autre que le sien et n'assume aucune responsabilité 
    concernant ces sites ou leurs contenus.
    La Panam Squad ne garantit pas l'absence d'erreurs typographiques, d'imprécisions ou 
    d'inexactitudes techniques sur le site.
    </p>

    <h3>Protection des données personnelles</h3>
    <p>
    La Panam Squad est susceptible de collecter et traiter des données à caractère 
    personnel des visiteurs de son site Internet, en tant que Responsable de Traitement,
    au sens de la Loi n° 78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers 
    et aux libertés modifiée et du Règlement Général sur la Protection des Données.

    Par données à caractère personnel, nous entendons, conformément à la Loi Informatique 
    et Libertés et le RGPD, toute information relative à une personne physique identifiée
    ou qui peut être identifiée, directement ou indirectement, par référence à un numéro 
    d'identification ou à un ou plusieurs éléments qui lui sont propres.

    La Panam Squad est attachée au respect et à la protection de la vie privée. Elle 
    s'engage à définir et appliquer les mesures adéquates afin de garantir la sécurité de vos données personnelles.
    </p>

    <h3>Utilisation faite des données</h3>
    <p>
    Les données à caractère personnel recueillies via l'intranet de la Panam Squad,
    le sont dans le but d'assurer les services et la gestion interne et externe de la 
    Panam Squad, notamment :
    <ul>
      <li>Gérer les adhésions, votes, et autres procédures inhérentes à la vie d'une association sportive</li>
      <li>Gérer les activités des membres de la Panam Squad (y compris leurs déplacements groupés)</li>
      <li>Gérer un calendrier d'événements internes comme externes</li>
      <li>Gérer un suivi des licenses FFRS</li>
    </ul>
    </p>

    <h3>Destinataire des données</h3>
    <p>
    Les données collectées sur l'intranet de la Panam Squad sont réservées à l'usage de la Panam Squad.
    Elles seront cependant en partie restransmises à la Fédération Française de Rollers et SkateBoard
    dans le but d'acquérir une license fédérale.
    </p>

    <h3>Conservation des données</h3>
    <p>
      Sauf règlement spécifique applicable, la Panam Squad conserve les données personnelles
      collectées pendant la durée justifiée par la finalité de leur traitement.
    </p>

    <h3>Vos droits</h3>
    <p>
    Conformément à la Loi Informatique et Libertés et le RGPD, vous disposez entre autres d'un droit d'accès,
    de rectification et d'opposition aux données personnelles vous concernant.

    Pour en savoir plus, consultez vos droits sur le site de la CNIL.
    </p>

    <h3>Droit de propriété intellectuelle</h3>
    <p>
    L'intranet de la Panam Squad est protégé par le droit d'auteur. Le code source, basé sur le framework Django est libre
    et publié sur <a href="https://github.com/the-mandarine/mypanamsquad">GitHub</a> sous license BeerWare.
    </p>
  </div>

{% endblock %}