docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>', views.detail, name="detail"),
    path(r'r/<slug>', views.redir, name="redir"),
]

opinions/urls.py
from django.urls import path
from . import views

app_name = 'opinions'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'<slug>/', views.detail, name="detail"),
    path(r'<slug>/results', views.results, name="results"),
    path(r'<slug>/express', views.express, name="express"),
]

opinions/models.py
from django.db import models
from django.contrib.auth.models import User
from infos.models import Profile, ProfileGroup
from datetime import datetime
from pytz import timezone
from django.conf import settings

TZ = timezone(settings.TIME_ZONE)

# Create your models here.
class OpinionQuestion(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    can_see_answers = models.ManyToManyField(Profile, related_name='validators', blank=True)
    can_answer = models.ManyToManyField(Profile, related_name='answerers', blank=True)
    group_can_see_answers = models.ManyToManyField(ProfileGroup, related_name='can_answer_to', blank=True)
    has_answered = models.ManyToManyField(Profile, related_name='answered_to', blank=True, editable=False)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class OpinionSubQuestion(models.Model):
    question = models.ForeignKey(OpinionQuestion, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text[:120]


class Opinion(models.Model):
    question = models.ForeignKey(OpinionQuestion, on_delete=models.CASCADE)
    date = models.DateTimeField()
    text = models.TextField()
    def __str__(self):
        return "[%s] %s" % (self.date,  self.text[:150])

opinions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views import generic

from opinions.models import OpinionQuestion, OpinionSubQuestion, Opinion
from datetime import datetime
from pytz import timezone
from django.conf import settings

TZ = timezone(settings.TIME_ZONE)

def has_been_checked(user):
    valid = False
    try:
        valid = user.profile.has_been_checked
    except:
        valid = False
    return valid

def can_see_answers(user, opinion_question):
    user_in_allowed_group = any([user.profile in p_g.profiles.all() for p_g in opinion_question.group_can_see_answers.all()])
    user_is_allowed = user.profile in opinion_question.can_see_answers.all()
    return user_is_allowed or user_in_allowed_group

@user_passes_test(has_been_checked)
def index(request):
    user = request.user
    now = TZ.localize(datetime.now())
    opinion_questions = OpinionQuestion.objects.filter()
    context = {'opinion_questions': opinion_questions}
    return render(request, 'opinions/index.html', context)

@user_passes_test(has_been_checked)
def detail(request, slug):
    now = TZ.localize(datetime.now())
    opinion_question = get_object_or_404(OpinionQuestion, slug=slug)
    subquestions = OpinionSubQuestion.objects.filter(question=opinion_question)
    can_answer = request.user.profile in opinion_question.can_answer.all()
    has_answered = request.user.profile in opinion_question.has_answered.all()
    user = request.user
    return render(request, 'opinions/detail.html', {
        'opinion_question': opinion_question,
        'subquestions': subquestions,
        'has_answered': has_answered,
        'can_answer': can_answer,
        'can_see_answers': can_see_answers(user, opinion_question)
    })

@user_passes_test(has_been_checked)
def express(request, slug):
    now = TZ.localize(datetime.now())
    opinion_question = get_object_or_404(OpinionQuestion, slug=slug)
    answer_text = request.POST.getlist('answer_text[]')
    stored_answer = answer_text
    if len(answer_text) >= 2:
        stored_answer = ""
        for field in answer_text:
            if field[:3] != 'Q: ':
                stored_answer += 'A: '+field
            else:
                stored_answer += field
            stored_answer += '\n'

    answer_date = datetime.now()
    if request.user.profile in opinion_question.can_answer.all() and request.user.profile not in opinion_question.has_answered.all():
        opinion = Opinion()
        opinion.question = opinion_question
        opinion.date = answer_date
        opinion.text = stored_answer
        opinion.save()
        opinion_question.has_answered.add(request.user.profile)
        opinion_question.save()
    return HttpResponseRedirect(reverse('opinions:detail', args=(slug,)))

@user_passes_test(has_been_checked)
def results(request, slug):
    now = TZ.localize(datetime.now())
    opinion_question = get_object_or_404(OpinionQuestion, slug=slug)
    user = request.user
    if can_see_answers(user, opinion_question):
        return render(request, 'opinions/results.html', {'opinion_question': opinion_question})
    else:
        return HttpResponseRedirect(reverse('opinions:detail', args=(slug,)))

opinions/templates/opinions/detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="cover">
  <h1 class="cover-heading">{{ opinion_question.name }}</h1>
  <div class="lead">
{% if error_message %}
<div class="alert alert-info" role="alert">
  {{ error_message }}
</div>
{% endif %}

<div class="alert alert-info lead" style="line-height: 150%;">
{{ opinion_question.text|linebreaks }}
</div>
  <div>
{% if opinion_question.archived %}
<p class="alert alert-warning">
Ce sondage est archivé.
</p>
{% elif not can_answer %}
<p class="alert alert-warning">
Vous ne pouvez pas répondre à ce sondage !
</p>
{% elif has_answered %}
<p class="alert alert-success">
Merci d'avoir répondu !
</p>
{% else %}
<form class="lead" action="{% url 'opinions:express' opinion_question.slug %}" method="post">
{% csrf_token %}
{% if not subquestions %}
  <div class="form-group">
    <textarea class="form-control" rows="10" name="answer_text[]"></textarea>
  </div>
{% else %}
<input type="hidden" name="with_subquestions" value="1" />
{% for subquestion in subquestions %}
<div class="alert alert-info lead">
{{ subquestion.text|linebreaks }}
<textarea style="visibility: hidden; position: absolute;" name="answer_text[]">Q: {{ subquestion.text }} &#8647;</textarea>
</div>
  <div class="form-group">
    <textarea class="form-control" rows="4" name="answer_text[]"></textarea>
  </div>
{% endfor %}
{% endif %}
  <input class="form-control btn btn-default" type="submit" value="m'exprimer" />
</form>
{% endif %}
{% if can_see_answers %}
  <p>
    <a href="{% url 'opinions:results' opinion_question.slug %}">Voir les réponses</a>
  </p>
{% endif  %}
  </div>
{% endblock %}

opinions/templates/opinions/index.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <h1 class="cover-heading">
    <span class="glyphicon glyphicon-comment">&nbsp;</span>
    Opinions
  </h1>
  <div class="lead">
    <ul>
    {% for opinion_question in opinion_questions %}
      <li>
        <a href="{% url 'opinions:detail' opinion_question.slug %}" title="{{ opinion_question.text }}">{{ opinion_question.name }}</a>
      </li>
    {% endfor %}
    </tbody>
    </table>
  </div>
</div>
{% endblock %}

opinions/templates/opinions/results.html
{% extends 'base.html' %}
{% block content %}
<div class="cover">
  <h1 class="cover-heading">{{ opinion_question.name }}</h1>
  <div class="alert alert-info lead" style="line-height: 150%;">
    {{ opinion_question.text|linebreaks }}
  </div>
{% for opinion in opinion_question.opinion_set.all %}
    <div>
    <b>{{ opinion.date }}</b>
    <blockquote class="blockquote">
    {{ opinion.text|linebreaks }}
    </blockquote>
    </div>
{% endfor %}
</div>
{% endblock %}